/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#d0cbc3",
        "secondary-container": "#ffdad6",
        "background": "#f5f0e8",
        "inverse-surface": "#1a1a1a",
        "primary-fixed-dim": "#e6b800",
        "on-surface": "#1a1a1a",
        "on-tertiary-fixed": "#1a1a1a",
        "tertiary-fixed": "#d6e3ff",
        "surface-container-lowest": "#ffffff",
        "outline": "#1a1a1a",
        "error-container": "#ffdad6",
        "error": "#cc0000",
        "secondary-fixed": "#ffdad6",
        "inverse-on-surface": "#f5f0e8",
        "tertiary": "#0055ff",
        "on-tertiary-fixed-variant": "#1a1a1a",
        "surface-variant": "#e8e3da",
        "surface-tint": "#1a1a1a",
        "surface-container-high": "#e8e3da",
        "on-secondary-fixed-variant": "#1a1a1a",
        "on-tertiary": "#ffffff",
        "on-secondary": "#1a1a1a",
        "on-primary-fixed": "#1a1a1a",
        "surface-dim": "#d6d1c9",
        "surface-bright": "#faf7f2",
        "surface": "#f5f0e8",
        "primary": "#1a1a1a",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2ede5",
        "surface-container": "#eee9e0",
        "secondary": "#e63b2e",
        "on-primary-container": "#1a1a1a",
        "on-secondary-fixed": "#1a1a1a",
        "inverse-primary": "#f5f0e8",
        "on-surface-variant": "#4a4a4a",
        "on-secondary-container": "#1a1a1a",
        "on-primary-fixed-variant": "#1a1a1a",
        "on-background": "#1a1a1a",
        "tertiary-fixed-dim": "#a8c6ff",
        "secondary-fixed-dim": "#ffb3ab",
        "on-tertiary-container": "#1a1a1a",
        "tertiary-container": "#d6e3ff",
        "primary-container": "#ffcc00",
        "on-error": "#ffffff",
        "primary-fixed": "#ffcc00",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e2ddd4"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
